### PR TITLE
Re-enable text prediction

### PR DESCRIPTION
**Pull request by Heroico**
@liangyy I think this change will re-enable text-based predictions in `Predict.py` and `PrediXcan.py`

### CODE REVIEW

**Comment by liangyy** [comment]
Hi @Heroico, I edited `enter` functions unnecessarily for [https://github.com/hakyimlab/MetaXcan/pull/113](url). Thanks for fixing it.

**Comment by Heroico** [comment]
@liangyy should we just merge this?

**Comment by Heroico** [comment]
> Hi @Heroico, I edited `enter` functions unnecessarily for [https://github.com/hakyimlab/MetaXcan/pull/113](url). Thanks for fixing it.

Unfortunately I can't access that pull request URL (I get 404 error) - maybe once things are merged, they become unavailable?

**Comment by liangyy** [comment]
Sorry, it seems that the embedded url is wrong there. Please try this: [https://github.com/hakyimlab/MetaXcan/pull/113](https://github.com/hakyimlab/MetaXcan/pull/113)

**Comment by Heroico** [comment]
Thanks for the clarification!

**Pull request merged**
